# taken from https://github.com/peaceiris/actions-gh-pages
# this was the Node.js example
# switched to use personal token
# note: this only works for deployments to master!

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # trying to use the methods from https://stackoverflow.com/questions/58139175/running-actions-in-another-directory
      - name: npm CI
        working-directory: ./client
        run: npm ci
      - name: npm build
        working-directory: ./client
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/dist
          allow_empty_commit: true
          enable_jekyll: false
          publish_branch: gh-pages
